using DentalClinicApp.Data; using DentalClinicApp.DTOs; using DentalClinicApp.Models;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace DentalClinicApp.Controllers;
[ApiController, Route("api/dentists")]
public class DentistsController : ControllerBase
{
 private readonly AppDbContext _db; public DentistsController(AppDbContext db)=>_db=db;
 [HttpGet] public async Task<ActionResult<PagedResponse<DentistResponse>>> Get(string? name,string? specialty,int page=1,int pageSize=10){ var q=_db.Dentists.AsQueryable(); if(!string.IsNullOrWhiteSpace(name)) q=q.Where(x=>x.FullName.Contains(name)); if(!string.IsNullOrWhiteSpace(specialty)) q=q.Where(x=>x.Specialty.Contains(specialty)); var total=await q.CountAsync(); var items=await q.OrderBy(x=>x.FullName).Skip((page-1)*pageSize).Take(pageSize).Select(x=>new DentistResponse(x.Id,x.FullName,x.Specialty,x.PhoneNumber,x.Email,x.Bio,x.ConsultationPrice,x.IsActive)).ToListAsync(); return Ok(new PagedResponse<DentistResponse>(items,total,page,pageSize));}
 [HttpGet("{id:int}")] public async Task<ActionResult<DentistResponse>> GetById(int id){ var x=await _db.Dentists.FindAsync(id); return x==null?NotFound(new ErrorResponse(404,"Dentist not found")):Ok(new DentistResponse(x.Id,x.FullName,x.Specialty,x.PhoneNumber,x.Email,x.Bio,x.ConsultationPrice,x.IsActive));}
 [HttpPost, Authorize(Roles="Admin")] public async Task<ActionResult<DentistResponse>> Create(DentistRequest r){ if(await _db.Dentists.AnyAsync(x=>x.Email==r.Email)) return Conflict(new ErrorResponse(409,"Dentist email already exists")); var x=new Dentist{FullName=r.FullName,Specialty=r.Specialty,PhoneNumber=r.PhoneNumber,Email=r.Email,Bio=r.Bio,ConsultationPrice=r.ConsultationPrice}; _db.Dentists.Add(x); await _db.SaveChangesAsync(); return CreatedAtAction(nameof(GetById),new{id=x.Id},new DentistResponse(x.Id,x.FullName,x.Specialty,x.PhoneNumber,x.Email,x.Bio,x.ConsultationPrice,x.IsActive));}
 [HttpPut("{id:int}"), Authorize(Roles="Admin")] public async Task<ActionResult<DentistResponse>> Update(int id,DentistRequest r){ var x=await _db.Dentists.FindAsync(id)??throw new KeyNotFoundException("Dentist not found"); x.FullName=r.FullName;x.Specialty=r.Specialty;x.PhoneNumber=r.PhoneNumber;x.Email=r.Email;x.Bio=r.Bio;x.ConsultationPrice=r.ConsultationPrice; await _db.SaveChangesAsync(); return Ok(new DentistResponse(x.Id,x.FullName,x.Specialty,x.PhoneNumber,x.Email,x.Bio,x.ConsultationPrice,x.IsActive));}
 [HttpDelete("{id:int}"), Authorize(Roles="Admin")] public async Task<IActionResult> Delete(int id){ if(await _db.Appointments.AnyAsync(x=>x.DentistId==id&&x.AppointmentDate>=DateOnly.FromDateTime(DateTime.Today)&&x.Status==AppointmentStatus.Scheduled)) return Conflict(new ErrorResponse(409,"Dentist has future appointments")); var x=await _db.Dentists.FindAsync(id)??throw new KeyNotFoundException("Dentist not found"); _db.Dentists.Remove(x); await _db.SaveChangesAsync(); return NoContent();}
}
