using DentalClinicApp.Data; using DentalClinicApp.DTOs;
using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using DentalClinicApp.Models;
namespace DentalClinicApp.Controllers;
[ApiController, Route("api/schedules")]
public class SchedulesController:ControllerBase
{ private readonly AppDbContext _db; public SchedulesController(AppDbContext db)=>_db=db;
 [HttpGet] public async Task<ActionResult<IEnumerable<ScheduleResponse>>> Get(int? dentistId, DateOnly? date){ var q=_db.Schedules.Include(x=>x.Dentist).AsQueryable(); if(dentistId.HasValue) q=q.Where(x=>x.DentistId==dentistId); if(date.HasValue) q=q.Where(x=>x.Date==date); return Ok(await q.OrderBy(x=>x.Date).ThenBy(x=>x.StartTime).Select(x=>new ScheduleResponse(x.Id,x.DentistId,x.Dentist!.FullName,x.Date,x.StartTime,x.EndTime,x.IsAvailable,x.Notes)).ToListAsync());}
 [HttpPost, Authorize(Roles="Admin")] public async Task<ActionResult<ScheduleResponse>> Create(ScheduleRequest r){ if(r.EndTime<=r.StartTime) return BadRequest(new ErrorResponse(400,"End time must be after start time")); if(!await _db.Dentists.AnyAsync(x=>x.Id==r.DentistId)) return NotFound(new ErrorResponse(404,"Dentist not found")); var overlap=await _db.Schedules.AnyAsync(x=>x.DentistId==r.DentistId&&x.Date==r.Date&&r.StartTime<x.EndTime&&r.EndTime>x.StartTime); if(overlap) return Conflict(new ErrorResponse(409,"Overlapping schedule exists")); var x=new Schedule{DentistId=r.DentistId,Date=r.Date,StartTime=r.StartTime,EndTime=r.EndTime,IsAvailable=r.IsAvailable,Notes=r.Notes}; _db.Schedules.Add(x); await _db.SaveChangesAsync(); return Ok(new MessageResponse("Schedule created successfully"));}
 [HttpPut("{id:int}"), Authorize(Roles="Admin")] public async Task<IActionResult> Update(int id,ScheduleRequest r){ var x=await _db.Schedules.FindAsync(id)??throw new KeyNotFoundException("Schedule not found"); if(r.EndTime<=r.StartTime) return BadRequest(new ErrorResponse(400,"End time must be after start time")); x.DentistId=r.DentistId;x.Date=r.Date;x.StartTime=r.StartTime;x.EndTime=r.EndTime;x.IsAvailable=r.IsAvailable;x.Notes=r.Notes; await _db.SaveChangesAsync(); return Ok(new MessageResponse("Schedule updated successfully"));}
 [HttpDelete("{id:int}"), Authorize(Roles="Admin")] public async Task<IActionResult> Delete(int id){ var x=await _db.Schedules.FindAsync(id)??throw new KeyNotFoundException("Schedule not found"); var has=await _db.Appointments.AnyAsync(a=>a.DentistId==x.DentistId&&a.AppointmentDate==x.Date&&a.Status==AppointmentStatus.Scheduled); if(has) return Conflict(new ErrorResponse(409,"Schedule has active appointments")); _db.Schedules.Remove(x); await _db.SaveChangesAsync(); return NoContent();}
}
